FROM node:8

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing front-end module of an Audiopyle app"

# EXPOSE HTTP PORT
EXPOSE 8008

RUN groupadd -g 999 -r audiopyle && useradd -m -r -u 999 -g audiopyle audiopyle
USER audiopyle
WORKDIR /home/audiopyle
COPY ./* ./

USER root
RUN chown -R audiopyle:audiopyle ./* && chmod u+x ./*.sh

USER audiopyle
RUN npm install

# DEFINE ENTRY POINT AS AUDIOPYLE UI
ENTRYPOINT ["./start_ui.sh"]