sudo: required
language: python
cache: pip
python:
    - "3.6"

services:
  - docker

before_script:
  - chmod u+x **/*.sh
  - sudo apt-get install -y libav-tools
  - make config

script:
  - make test
  - make build
  - make basedocker
  - make docker
  - make verify

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/push_images.sh $DOCKER_USERNAME $DOCKER_PASSWORD;
    fi

notifications:
  email:
    on_success: never
    on_failure: change