FROM emkor/audiopyle-lib

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing API module of an Audiopyle app"

# EXPOSE HTTP PORT
EXPOSE 8080

# COPY STARTUP SCRIPT AND SET PERMISSIONS
USER root
WORKDIR /home/audiopyle
COPY start_api.sh ./start_api.sh
RUN chown audiopyle:audiopyle ./start_api.sh && chmod u+x ./start_api.sh
USER audiopyle

# DEFINE ENTRY POINT AS AUDIOPYLE API
ENTRYPOINT ["./start_api.sh"]