FROM emkor/audiopyle-lib

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing worker module of an Audiopyle app"

# EXPOSE PORTS
EXPOSE 8080

# DEFINE ENTRY POINT AS AUDIOPYLE WORKER
ENTRYPOINT ["/audiopyle/wait-for-it.sh", "-t", "15", "rabbitmq:5672", "--", "audiopyle-worker"]
