FROM emkor/audiopyle-base

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing libraries of an Audiopyle app"

# SET WORK DIRECTORY
WORKDIR /audiopyle

# INSTALL AUDIOPYLE
COPY audiopyle-*.whl .
RUN pip install --no-cache-dir ./audiopyle-*.whl
RUN rm ./audiopyle-*.whl

# DUMMY ENTRY POINT
CMD ["/bin/bash"]