FROM emkor/audiopyle-base

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing libraries of an Audiopyle app"

# ADD AUDIOPYLE PACKAGE; EXECUTED AS ROOT
USER root
COPY audiopyle-*.whl /home/audiopyle/
RUN chown audiopyle:audiopyle /home/audiopyle/*.whl

# SET WORK DIRECTORY AND USER, INSTALL AUDIOPYLE
USER audiopyle
WORKDIR /home/audiopyle
RUN . /home/audiopyle/.venv/bin/activate && pip install --no-cache-dir ./audiopyle-*.whl && rm ./audiopyle-*.whl

# DUMMY ENTRY POINT
CMD ["/bin/bash"]