FROM emkor/audiopyle-lib

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing API module of an Audiopyle app"

# EXPOSE HTTP PORT
EXPOSE 8080

# DEFINE ENTRY POINT AS AUDIOPYLE API
ENTRYPOINT ["/audiopyle/wait-for-it.sh", "-t", "15", "mysql:3306", "--", "/audiopyle/wait-for-it.sh", "-t", "15", "rabbitmq:5672", "--", "audiopyle-api"]