FROM emkor/audiopyle-commons

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing Coordinator module of an audiopyle app"

# EXTRACTOR DIRS ARE INHERITED

# SET WORKDIR
WORKDIR /audiopyle

# ESPOSE HTTP PORT
EXPOSE 8080

# DEFINE ENTRYPOINT AS COORDINATOR API
ENTRYPOINT ["/audiopyle/wait-for-it.sh", "-t", "15", "mysql:3306", "--", "/audiopyle/wait-for-it.sh", "-t", "15", "rabbitmq:5672", "--", "coordinator"]