FROM emkor/audiopyle-worker

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing integration tests"

# COPY STARTUP SCRIPT AND SET PERMISSIONS
USER root
WORKDIR /home/audiopyle
COPY start_testcases.sh ./start_testcases.sh
RUN chown audiopyle:audiopyle ./start_testcases.sh && chmod u+x ./start_testcases.sh
USER audiopyle

# CREATE AND SET DIRECTORIES
ENTRYPOINT "./start_testcases.sh"
