FROM emkor/audiopyle-lib

MAINTAINER emkor93@gmail.com
LABEL version="0.1"
LABEL description="Image containing worker module of an Audiopyle app"

# COPY STARTUP SCRIPT AND SET PERMISSIONS
USER root
WORKDIR /home/audiopyle
COPY start_worker.sh ./start_worker.sh
RUN chown audiopyle:audiopyle ./start_worker.sh && chmod u+x ./start_worker.sh
USER audiopyle

# DEFINE ENTRY POINT AS AUDIOPYLE WORKER
ENTRYPOINT ["./start_worker.sh"]
