# Generated by Django 2.0.2 on 2018-02-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VampyPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VampyPluginCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VampyPluginOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vampy_plugin.VampyPlugin')),
            ],
        ),
        migrations.AddField(
            model_name='vampyplugin',
            name='categories',
            field=models.ManyToManyField(to='vampy_plugin.VampyPluginCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='vampyplugin',
            unique_together={('provider', 'name')},
        ),
    ]
